DROP PROCEDURE IF EXISTS car_model_creation_datetime;;

CREATE FUNCTION car_model_creation_datetime(brand_id INT)
    RETURNS DATETIME
    NOT DETERMINISTIC
    READS SQL DATA
BEGIN
    DECLARE model_creation DATETIME;
    SET model_creation := FROM_UNIXTIME(RAND() * (UNIX_TIMESTAMP((SELECT TIMESTAMP(brands.created) FROM brands WHERE id = brand_id)) - UNIX_TIMESTAMP(NOW())) + UNIX_TIMESTAMP(NOW()));
    RETURN model_creation;
END;;

INSERT INTO models (name, brand_id, created)
VALUES ('Acura MODEL 1', 1, (SELECT car_model_creation_datetime(1))),
       ('Acura MODEL 2', 1, (SELECT car_model_creation_datetime(1))),
       ('Alfa-Romeo MODEL 1', 2, (SELECT car_model_creation_datetime(2))),
       ('Aston Martin MODEL 1', 3, (SELECT car_model_creation_datetime(3))),
       ('Audi MODEL 1', 4, (SELECT car_model_creation_datetime(4))),
       ('Audi MODEL 2', 4, (SELECT car_model_creation_datetime(4))),
       ('Audi MODEL 3', 4, (SELECT car_model_creation_datetime(4))),
       ('Audi MODEL 4', 4, (SELECT car_model_creation_datetime(4))),
       ('BMW MODEL 1', 5, (SELECT car_model_creation_datetime(5))),
       ('BMW MODEL 2', 5, (SELECT car_model_creation_datetime(5))),
       ('BMW MODEL 3', 5, (SELECT car_model_creation_datetime(5))),
       ('BMW MODEL 4', 5, (SELECT car_model_creation_datetime(5))),
       ('BMW MODEL 5', 5, (SELECT car_model_creation_datetime(5))),
       ('Bentley MODEL 1', 6, (SELECT car_model_creation_datetime(6))),
       ('Buick MODEL 1', 7, (SELECT car_model_creation_datetime(7))),
       ('Cadillac MODEL 1', 8, (SELECT car_model_creation_datetime(8))),
       ('Chevrolet MODEL 1', 9, (SELECT car_model_creation_datetime(9))),
       ('Chevrolet MODEL 2', 9, (SELECT car_model_creation_datetime(9))),
       ('Chrysler MODEL 1', 10, (SELECT car_model_creation_datetime(10))),
       ('Daewoo MODEL 1', 11, (SELECT car_model_creation_datetime(11))),
       ('Daihatsu MODEL 1', 12, (SELECT car_model_creation_datetime(12))),
       ('Dodge MODEL 1', 13, (SELECT car_model_creation_datetime(13))),
       ('Dodge MODEL 2', 13, (SELECT car_model_creation_datetime(13))),
       ('Eagle MODEL 1', 14, (SELECT car_model_creation_datetime(14))),
       ('Ferrari MODEL 1', 15, (SELECT car_model_creation_datetime(15))),
       ('Ferrari MODEL 2', 15, (SELECT car_model_creation_datetime(15))),
       ('Ferrari MODEL 3', 15, (SELECT car_model_creation_datetime(15))),
       ('Fiat MODEL 1', 16, (SELECT car_model_creation_datetime(16))),
       ('Fiat MODEL 2', 16, (SELECT car_model_creation_datetime(16))),
       ('Fisker MODEL 1', 17, (SELECT car_model_creation_datetime(17))),
       ('Ford MODEL 1', 18, (SELECT car_model_creation_datetime(18))),
       ('Ford MODEL 2', 18, (SELECT car_model_creation_datetime(18))),
       ('Ford MODEL 3', 18, (SELECT car_model_creation_datetime(18))),
       ('Freightliner MODEL 1', 19, (SELECT car_model_creation_datetime(19))),
       ('GMC MODEL 1', 20, (SELECT car_model_creation_datetime(20))),
       ('GMC MODEL 2', 20, (SELECT car_model_creation_datetime(20))),
       ('Genesis MODEL 1', 21, (SELECT car_model_creation_datetime(21))),
       ('Geo MODEL 1', 22, (SELECT car_model_creation_datetime(22))),
       ('Honda MODEL 1', 23, (SELECT car_model_creation_datetime(23))),
       ('Honda MODEL 2', 23, (SELECT car_model_creation_datetime(23))),
       ('Honda MODEL 3', 23, (SELECT car_model_creation_datetime(23))),
       ('Honda MODEL 4', 23, (SELECT car_model_creation_datetime(23))),
       ('Hummer MODEL 1', 24, (SELECT car_model_creation_datetime(24))),
       ('Hummer MODEL 1', 24, (SELECT car_model_creation_datetime(24))),
       ('Hyundai MODEL 1', 25, (SELECT car_model_creation_datetime(25))),
       ('Hyundai MODEL 2', 25, (SELECT car_model_creation_datetime(25))),
       ('Infinity MODEL 1', 26, (SELECT car_model_creation_datetime(26))),
       ('Infinity MODEL 2', 26, (SELECT car_model_creation_datetime(26))),
       ('Isuzu MODEL 1', 27, (SELECT car_model_creation_datetime(27))),
       ('Jaguar MODEL 1', 28, (SELECT car_model_creation_datetime(28))),
       ('Jaguar MODEL 2', 28, (SELECT car_model_creation_datetime(28))),
       ('Jeep MODEL 1', 29, (SELECT car_model_creation_datetime(29))),
       ('Jeep MODEL 2', 29, (SELECT car_model_creation_datetime(29))),
       ('Kia MODEL 1', 30, (SELECT car_model_creation_datetime(30))),
       ('Kia MODEL 2', 30, (SELECT car_model_creation_datetime(30))),
       ('Kia MODEL 3', 30, (SELECT car_model_creation_datetime(30))),
       ('Lamborghini MODEL 1', 31, (SELECT car_model_creation_datetime(31))),
       ('Lamborghini MODEL 2', 31, (SELECT car_model_creation_datetime(31))),
       ('Lamborghini MODEL 3', 31, (SELECT car_model_creation_datetime(31))),
       ('Land Rover MODEL 1', 32, (SELECT car_model_creation_datetime(32))),
       ('Lexus MODEL 1', 33, (SELECT car_model_creation_datetime(33))),
       ('Lexus MODEL 2', 33, (SELECT car_model_creation_datetime(33))),
       ('Lincoln MODEL 1', 34, (SELECT car_model_creation_datetime(34))),
       ('Lotus MODEL 1', 35, (SELECT car_model_creation_datetime(35))),
       ('Mazda MODEL 1', 36, (SELECT car_model_creation_datetime(36))),
       ('Mazda MODEL 2', 36, (SELECT car_model_creation_datetime(36))),
       ('Mazda MODEL 3', 36, (SELECT car_model_creation_datetime(36))),
       ('Maserati MODEL 1', 37, (SELECT car_model_creation_datetime(37))),
       ('Maserati MODEL 2', 37, (SELECT car_model_creation_datetime(37))),
       ('Maybach MODEL 1', 38, (SELECT car_model_creation_datetime(38))),
       ('Maybach MODEL 2', 38, (SELECT car_model_creation_datetime(38))),
       ('McLaren MODEL 1', 39, (SELECT car_model_creation_datetime(39))),
       ('McLaren MODEL 2', 39, (SELECT car_model_creation_datetime(39))),
       ('Mercedes-Benz MODEL 1', 40, (SELECT car_model_creation_datetime(40))),
       ('Mercedes-Benz MODEL 2', 40, (SELECT car_model_creation_datetime(40))),
       ('Mercedes-Benz MODEL 3', 40, (SELECT car_model_creation_datetime(40))),
       ('Mercedes-Benz MODEL 4', 40, (SELECT car_model_creation_datetime(40))),
       ('Mercedes-Benz MODEL 5', 40, (SELECT car_model_creation_datetime(40))),
       ('Mercury MODEL 1', 41, (SELECT car_model_creation_datetime(41))),
       ('Mini MODEL 1', 42, (SELECT car_model_creation_datetime(42))),
       ('Mini MODEL 2', 42, (SELECT car_model_creation_datetime(42))),
       ('Mitsubishi MODEL 1', 43, (SELECT car_model_creation_datetime(43))),
       ('Mitsubishi MODEL 2', 43, (SELECT car_model_creation_datetime(43))),
       ('Mitsubishi MODEL 3', 43, (SELECT car_model_creation_datetime(43))),
       ('Nissan MODEL 1', 44, (SELECT car_model_creation_datetime(44))),
       ('Nissan MODEL 2', 44, (SELECT car_model_creation_datetime(44))),
       ('Nissan MODEL 3', 44, (SELECT car_model_creation_datetime(44))),
       ('Nissan MODEL 4', 44, (SELECT car_model_creation_datetime(44))),
       ('Oldsmobile MODEL 1', 45, (SELECT car_model_creation_datetime(45))),
       ('Panoz MODEL 1', 46, (SELECT car_model_creation_datetime(46))),
       ('Plymouth MODEL 1', 47, (SELECT car_model_creation_datetime(47))),
       ('Polestar MODEL 1', 48, (SELECT car_model_creation_datetime(48))),
       ('Pontiac MODEL 1', 49, (SELECT car_model_creation_datetime(49))),
       ('Pontiac MODEL 2', 49, (SELECT car_model_creation_datetime(49))),
       ('Porsche MODEL 1', 50, (SELECT car_model_creation_datetime(50))),
       ('Porsche MODEL 2', 50, (SELECT car_model_creation_datetime(50))),
       ('Porsche MODEL 3', 50, (SELECT car_model_creation_datetime(50))),
       ('Porsche MODEL 4', 50, (SELECT car_model_creation_datetime(50))),
       ('Ram MODEL 1', 51, (SELECT car_model_creation_datetime(51))),
       ('Rivian MODEL 1', 52, (SELECT car_model_creation_datetime(52))),
       ('Rolls_Royce MODEL 1', 53, (SELECT car_model_creation_datetime(53))),
       ('Rolls_Royce MODEL 2', 53, (SELECT car_model_creation_datetime(53))),
       ('Rolls_Royce MODEL 3', 53, (SELECT car_model_creation_datetime(53))),
       ('Saab MODEL 1', 54, (SELECT car_model_creation_datetime(54))),
       ('Saab MODEL 2', 54, (SELECT car_model_creation_datetime(54))),
       ('Saturn MODEL 1', 55, (SELECT car_model_creation_datetime(55))),
       ('Smart MODEL 1', 56, (SELECT car_model_creation_datetime(56))),
       ('Smart MODEL 2', 56, (SELECT car_model_creation_datetime(56))),
       ('Subaru MODEL 1', 57, (SELECT car_model_creation_datetime(57))),
       ('Subaru MODEL 2', 57, (SELECT car_model_creation_datetime(57))),
       ('Subaru MODEL 3', 57, (SELECT car_model_creation_datetime(57))),
       ('Suzuki MODEL 1', 58, (SELECT car_model_creation_datetime(58))),
       ('Suzuki MODEL 2', 58, (SELECT car_model_creation_datetime(58))),
       ('Tesla MODEL 1', 59, (SELECT car_model_creation_datetime(59))),
       ('Tesla MODEL 2', 59, (SELECT car_model_creation_datetime(59))),
       ('Tesla MODEL 3', 59, (SELECT car_model_creation_datetime(59))),
       ('Tesla MODEL 4', 59, (SELECT car_model_creation_datetime(59))),
       ('Toyota MODEL 1', 60, (SELECT car_model_creation_datetime(60))),
       ('Toyota MODEL 2', 60, (SELECT car_model_creation_datetime(60))),
       ('Toyota MODEL 3', 60, (SELECT car_model_creation_datetime(60))),
       ('Toyota MODEL 4', 60, (SELECT car_model_creation_datetime(60))),
       ('Toyota MODEL 5', 60, (SELECT car_model_creation_datetime(60))),
       ('Toyota MODEL 6', 60, (SELECT car_model_creation_datetime(60))),
       ('Volkswagen MODEL 1', 61, (SELECT car_model_creation_datetime(61))),
       ('Volkswagen MODEL 2', 61, (SELECT car_model_creation_datetime(61))),
       ('Volkswagen MODEL 3', 61, (SELECT car_model_creation_datetime(61))),
       ('Volkswagen MODEL 4', 61, (SELECT car_model_creation_datetime(61))),
       ('Volkswagen MODEL 5', 61, (SELECT car_model_creation_datetime(61))),
       ('Volvo MODEL 1', 62, (SELECT car_model_creation_datetime(62))),
       ('Volvo MODEL 2', 62, (SELECT car_model_creation_datetime(62))),
       ('Volvo MODEL 3', 62, (SELECT car_model_creation_datetime(62))),
       ('Volvo MODEL 4', 62, (SELECT car_model_creation_datetime(62)));;
